version: "3"

services:
  nginx:
    container_name: yii-nginx
    image: nginx:1.17
    volumes:
      - ./src:/var/www/yii
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - php
    depends_on:
      - php

  php:
    container_name: yii-php
    image: yii-php
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./src:/var/www/yii
    ports:
      - 9000:9000
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: yii-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yii2basic
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=Etc/UTC
    restart: on-failure

  # redis:
  #   container_name: test-redis
  #   image: redis:5.0.5-buster
  #   ports:
  #     - 6379:6379
